export const bookMap = {
  // Antiguo Testamento
  "GEN": "Génesis",
  "EX": "Éxodo",
  "LEV": "Levítico",
  "NUM": "Números",
  "NM": "Números",
  "DEU": "Deuteronomio",
  "JOS": "Josué",
  "JUE": "Jueces",
  "RUT": "Rut",
  "1SAM": "1 Samuel",
  "2SAM": "2 Samuel",
  "1REY": "1 Reyes",
  "2REY": "2 Reyes",
  "1CRON": "1 Crónicas",
  "2CRON": "2 Crónicas",
  "EZRA": "Esdras",
  "NEH": "Nehemías",
  "EST": "Ester",
  "JOB": "Job",
  "SAL": "Salmos",
  "PRO": "Proverbios",
  "PR": "Proverbios",
  "ECL": "Eclesiastés",
  "CANT": "Cantar de los Cantares",
  "ISA": "Isaías",
  "IS": "Isaías",
  "JER": "Jeremías",
  "JR": "Jeremías",
  "LAMENT": "Lamentaciones",
  "EZE": "Ezequiel",
  "EZ": "Ezequiel",
  "DAN": "Daniel",
  "OSE": "Oseas",
  "JOEL": "Joel",
  "AMO": "Amós",
  "ABD": "Abdías",
  "JON": "Jonás",
  "MIC": "Miqueas",
  "MQ": "Miqueas",
  "MIQ": "Miqueas",
  "NAM": "Nahum",
  "HAB": "Habacuc",
  "SOF": "Sofonías",
  "HAG": "Hageo",
  "ZAC": "Zacarías",
  "MAL": "Malaquías",

  // Nuevo Testamento
  "MT": "Mateo",
  "MR": "Marcos",
  "LC": "Lucas",
  "LC.": "Lucas",
  "JN": "Juan",
  "HEB": "Hebreos",
  "HE": "Hebreos",
  "SANTI": "Santiago",
  "STG": "Santiago",
  "1PE": "1 Pedro",
  "HCH": "Hechos",
  "ROM": "Romanos",
  "RO": "Romanos",
  "1CO": "1 Corintios",
  "2CO": "2 Corintios",
  "GA": "Gálatas",
  "GAL": "Gálatas",
  "EF": "Efesios",
  "FIL": "Filipenses",
  "COL": "Colosenses",
  "1TES": "1 Tesalonicenses",
  "2TES": "2 Tesalonicenses",
  "1TIM": "1 Timoteo",
  "2TIM": "2 Timoteo",
  "TIT": "Tito",
  "1JN": "1 Juan",
  "2JN": "2 Juan",
  "3JN": "3 Juan",
  "JUD": "Judas",
  "APOC": "Apocalipsis",
  "AP": "Apocalipsis"
};
