// books.js
export const books = {
  'GEN': 'Génesis', 'GEN.': 'Génesis', 'GN': 'Génesis', 'GN.': 'Génesis',
  'EX': 'Éxodo', 'EX.': 'Éxodo',
  'LEV': 'Levítico', 'LEV.': 'Levítico',
  'NUM': 'Números', 'NUM.': 'Números', 'NM': 'Números', 'NM.': 'Números',
  'DEU': 'Deuteronomio', 'DEU.': 'Deuteronomio',
  'JOS': 'Josué', 'JOS.': 'Josué',
  'JUE': 'Jueces', 'JUE.': 'Jueces',
  'RUT': 'Rut', 'RUT.': 'Rut',
  '1 SAM': '1 Samuel', '1 SAM.': '1 Samuel',
  '2 SAM': '2 Samuel', '2 SAM.': '2 Samuel', '2SAM': '2 Samuel', '2SAM.': '2 Samuel',
  '1 REY': '1 Reyes', '1 REY.': '1 Reyes', '1RE': '1 Reyes', '1RE.': '1 Reyes',
  '2 REY': '2 Reyes', '2 REY.': '2 Reyes',
  '1 CRON': '1 Crónicas', '1 CRON.': '1 Crónicas',
  '2 CRON': '2 Crónicas', '2 CRON.': '2 Crónicas', '2CR': '2 Crónicas', '2CR.': '2 Crónicas',
  'EZRA': 'Esdras', 'EZRA.': 'Esdras',
  'NEH': 'Nehemías', 'NEH.': 'Nehemías',
  'EST': 'Ester', 'EST.': 'Ester',
  'JOB': 'Job', 'JOB.': 'Job',
  'SAL': 'Salmos', 'SAL.': 'Salmos',
  'PRO': 'Proverbios', 'PRO.': 'Proverbios', 'PR': 'Proverbios', 'PR.': 'Proverbios',
  'ECL': 'Eclesiastés', 'ECL.': 'Eclesiastés',
  'CANT': 'Cantar de los Cantares', 'CANT.': 'Cantar de los Cantares',
  'ISA': 'Isaías', 'ISA.': 'Isaías', 'IS': 'Isaías', 'IS.': 'Isaías',
  'JER': 'Jeremías', 'JER.': 'Jeremías', 'JR': 'Jeremías', 'JR.': 'Jeremías',
  'LAMENT': 'Lamentaciones', 'LAMENT.': 'Lamentaciones',
  'EZE': 'Ezequiel', 'EZE.': 'Ezequiel', 'EZ': 'Ezequiel', 'EZ.': 'Ezequiel',
  'DAN': 'Daniel', 'DAN.': 'Daniel',
  'OSE': 'Oseas', 'OSE.': 'Oseas',
  'JOEL': 'Joel', 'JOEL.': 'Joel',
  'AMO': 'Amós', 'AMO.': 'Amós',
  'ABD': 'Abdías', 'ABD.': 'Abdías',
  'JON': 'Jonás', 'JON.': 'Jonás',
  'MIC': 'Miqueas', 'MIC.': 'Miqueas', 'MQ': 'Miqueas', 'MQ.': 'Miqueas', 'MIQ': 'Miqueas', 'MIQ.': 'Miqueas',
  'NAM': 'Nahum', 'NAM.': 'Nahum',
  'HAB': 'Habacuc', 'HAB.': 'Habacuc',
  'SOF': 'Sofonías', 'SOF.': 'Sofonías',
  'HAG': 'Hageo', 'HAG.': 'Hageo',
  'ZAC': 'Zacarías', 'ZAC.': 'Zacarías',
  'MAL': 'Malaquías', 'MAL.': 'Malaquías',
  'MT': 'Mateo', 'MT.': 'Mateo',
  'MR': 'Marcos', 'MR.': 'Marcos',
  'LC': 'Lucas', 'LC.': 'Lucas',
  'JN': 'Juan', 'JN.': 'Juan',
  'HEB': 'Hebreos', 'HEB.': 'Hebreos', 'HE': 'Hebreos', 'HE.': 'Hebreos',
  'SANTI': 'Santiago', 'SANTI.': 'Santiago', 'STG.': 'Santiago',
  '1PE': '1 Pedro', '1PE.': '1 Pedro',
  'HCH': 'Hechos', 'HCH.': 'Hechos',
  'ROM': 'Romanos', 'ROM.': 'Romanos', 'RO': 'Romanos', 'RO.': 'Romanos',
  '1 CO': '1 Corintios', '1 CO.': '1 Corintios', '1CO': '1 Corintios', '1CO.': '1 Corintios',
  '2 CO': '2 Corintios', '2 CO.': '2 Corintios', '2CO': '2 Corintios', '2CO.': '2 Corintios', '2COR': '2 Corintios', '2COR.': '2 Corintios',
  'GA': 'Gálatas', 'GA.': 'Gálatas', 'GAL': 'Gálatas', 'GAL.': 'Gálatas',
  'EF': 'Efesios', 'EF.': 'Efesios',
  'FIL': 'Filipenses', 'FIL.': 'Filipenses',
  'COL': 'Colosenses', 'COL.': 'Colosenses',
  '1 TES': '1 Tesalonicenses', '1 TES.': '1 Tesalonicenses', '1TES.': '1 Tesalonicenses',
  '2 TES': '2 Tesalonicenses', '2 TES.': '2 Tesalonicenses',
  '1 TIM': '1 Timoteo', '1 TIM.': '1 Timoteo',
  '2 TIM': '2 Timoteo', '2 TIM.': '2 Timoteo', '2TIM.': '2 Timoteo',
  'TIT': 'Tito', 'TIT.': 'Tito',
  '1 JUAN': '1 Juan', '1 JUAN.': '1 Juan', '1JN': '1 Juan', '1JN.': '1 Juan',
  '2 JUAN': '2 Juan', '2 JUAN.': '2 Juan',
  '3 JUAN': '3 Juan', '3 JUAN.': '3 Juan',
  'JUD': 'Judas', 'JUD.': 'Judas',
  'APOC': 'Apocalipsis', 'APOC.': 'Apocalipsis', 'AP': 'Apocalipsis', 'AP.': 'Apocalipsis'
};

export default books;

